transfer:
  compress: true
  timeout_seconds: 60
  timeout_idle_seconds: 60

server:
  # use_profiler: true
  use_profiler: false
  proxy: localhost:9977
  # proxy: 0.0.0.0:9977

  # The server that receives the requests from the proxy server
  origin: http://localhost:9812
  real_ip_header: X-Real-IP

  # Prefork: Utilizes mutliple CPU cores. Note that this might even be slower than the default! Depends on the hardware, testing is required.
  prefork: false
  strict_routing: false
  case_sensitive: true
  body_limit_bytes: 1000000 # 1MB
  get_ip_from_header: ''
  enable_keep_alive: true

  read_timeout_seconds: 60
  write_timeout_seconds: 60
  idle_timeout_seconds: 60


antibot:
  # Anti-Bot is a set of JavaScript checks that is used to verify the authenticity of the client.
  enabled: true

  # 1000 = 100% certain that the client is a bot
  threshold: 500

  # During this time, no checks will be performed for the client
  # Can be very low for testing, but should be rather high for production
  verification_valid_for_seconds: 10

captcha:
  verification_valid_for_seconds: 10
  max_failed_attempts: 5
  max_failed_attempts_timespan_seconds: 10

other:
  obfuscate_javascript: true
